n=new Date,h=n.getHours(),$("title").html(21<h?"夜深了，注意休息。~":16<h?"晚上好!该做点什么呢。":13<h?"下午好!今天过的充实吧。":10<h?"中午好!忙了一早上了吧。":7<h?"早上好，新的一天开始了。":4<h?"早上好!":"还在修仙?")
setInterval('n=new Date,h=n.getHours(),m=n.getMinutes(),s=n.getSeconds(),T&&$("#lgo").html((h<10?"0"+h:h)+":"+(m<10?"0"+m:m)+(s%2?":":" ")+(s<10?"0"+s:s))')

var L=localStorage;
if(L.use||L.userdata)bak=L.use?L.bok:L.bookmark,L.clear(),L.bok=bak
if(!L.mnu||JSON.parse(L.mnu)[0][1]<3.5)L.setItem('mnu',JSON.stringify([["dta",3.5],["logo","时间",1,1,"#44bbff","#44ffbb",36,0,120,"Google","logo/google.png","<p style='font-size:40px'><b style='color:#48f'>G</b><b style='color:#e43'>o</b><b style='color:#fb0'>o</b><b style='color:#48f'>g</b><b style='color:#3a5'>l</b><b style='color:#e43'>e</b></p>"],["bg",1,"#f0f0f0","img/back.gif",0,1],["bar",500,300,"What","Go","https://www.baidu.com/s?wd="],["book",0,"#000000",5]]))
if(!L.bok||L.bok=='[]')L.setItem('bok',JSON.stringify([["百度","https://m.baidu.com/?pu=sz%401321_480","img/baidu.png"],["乐回享","http://echooit.com/","img/echooit.png"],["盘多多","http://m.panduoduo.net/","img/pdd.png"],["豆瓣","https://m.douban.com/movie/","img/db.png"],["海贼王","http://www.manhuaren.com/manhua-haizeiwang-onepiece","img/hzw.png"],["果核剥壳","http://www.ghboke.com/","img/ghbk.png"],["52破解","https://www.52pojie.cn/forum.php?mobile=no","img/52pj.png"],["移动叔叔","http://bbs.ydss.cn/forum.php?mod=forumdisplay&fid=780&mobile=2","img/ydss.png"],["雨滴社区","https://bbs.rainmeter.cn/plugin.php?id=dsu_paulsign:sign&mobile=yes","img/ydsq.png"],["IT热评","https://www.itreping.com/","img/IT.png"],["80s","https://m.80s.tw/","img/80s.png"],["Win10","http://m.xitongzhijia.net/channel/227/","img/win10.png"],["APKpure","https://m.apkpure.com/cn/","img/apkpure.png"],["Google","https://www.google.com.hk/","img/google.png"],["更多首页","http://leftshine.gitee.io/viaindex/","img/more.png"]]))
var B=JSON.parse(L.bok),C=JSON.parse(L.mnu),D=E=F=T=1
for(var a='',b=0;b<B.length;b++)a+='<li><div class="sc"></div><div class="bq" style="background-image:url('+B[b][2]+')" msg="'+B[b][1]+'"></div><p>'+B[b][0]+'</p></li>'
$('#book').html(a+'<li class="mark"><div class="tj" style="background-image:url(img/mark.png)"></div><p>添加书签</p></li>'),style(0)

$.fn.longPress=function(a){var b=void 0,c=this;for(d=c.length;d>0;d--)
c[d-1].addEventListener('touchstart',function(){b=setTimeout(a,700)},!1),
c[d-1].addEventListener('touchmove',function(){clearTimeout(b)},!1),
c[d-1].addEventListener('touchend',function(){clearTimeout(b)},!1)}
$('.ktext').on('input',function(){var a=$(this).val();$('.btext').html(a?a:'预览')})
$('#wqy').longPress('$(".wqy").slideDown(),$("#menus").animate({scrollTop:500},300)')
$('.backc').on('input',function(){a=$(this).val().match(/[a-f0-9]{6}/gi),a&&($('.backc').val(C[2][2]=b='#'+a).eq(0).css('background',b),style(2))})
$('.bq').longPress('if(D)D=E=0,$(".sc").fadeIn().css("margin-left",(a=$("#book li").width(),a>64?a/2+10:a-20)+"px"),$(".bq").length<20&&$(".mark").show()')
$('#submit').click(function(){a=$('#input').val();if(a)run(a);return !1}).longPress('$("#engine,#bar").slideToggle();for(var a=$("#engine li"),b=0;b<6;b++)a.eq(b).css(a.eq(b).attr("msg")!=C[3][5]?({"color":"#888","text-shadow":""}):({"color":"","text-shadow":"0 0 1px #555"}))')
$('.kicon').click(function(){a=$('.bicon');if($(this).attr('type')){$(this).on('input',function(){b=$(this).val(),c='img/jz.gif';b.match(/\.(png|jp(e?)g|gif)$/i)?a.attr('src',b):c!=a.attr('src')&&a.attr('src',c)})}else{$('#xfile').click().change(function(){b=new FileReader();$('.kicon').eq(0).val($(this).val()),b.readAsDataURL(this.files[0]),b.onload=function(){a.attr('src',this.result)}})}})
$('.logop,.backp').click(function(){var a=$(this).is('.backp');if($(this).attr('type')){$(this).on('input',function(){b=$(this).val();if(b.match(/\.(png|jp(e?)g|gif)$/i))style(a?(C[2][3]=b,2):(C[1][10]=b,1))})}else{$(a?'#bfile':'#pfile').click().change(function(){$(a?'.backp':'.logop').eq(0).val($(this).val()),b=new FileReader(),b.readAsDataURL(this.files[0]),b.onload=function(){style(a?(C[2][3]=this.result,2):(C[1][10]=this.result,1))}})}})
$('#input').on('keyup focus',function(){E=0,a=$(this).val(),$('#clear').css('display',a?(clearTimeout(b),'block'):(getdata(''),'')),$('#bar').stop().animate({'top':Math.abs(orientation)==90?'78%':C[3][1]+'px'},300),$('#book').hide();b=setTimeout('getdata(a)',C[3][2])}).blur(function(){if($(this).val()){$('#suglist').click(function(e){a=$(e.target),b=a.closest('li').text(),a.is('b')?$('#input').val(b).focus():run(b)})}else{E=1,$('#bar').stop().animate({'top':'30%'},300),$('#book').show()}})
$('.byes').click(function(){a=$('.ktext').val(),b=$('.khttp').val(),c=$('.bicon').attr('src');(a&&b&&c!='img/jz.gif')?(b=b.match(/^((ht|f)tp(s?)|file|folder):\/\//)?b:'http://'+b,cat==99?(B.push([a,b,c]),$('.mark').before('<li><div class="sc"></div><div class="bq" style="background-image:url('+c+')" msg="'+b+'"></div><p>'+a+'</p></li>')):(B.splice(cat,1,[a,b,c]),$('#book li').eq(cat).html('<div class="sc"></div><div class="bq" style="background-image:url('+c+')" msg="'+b+'"></div><p>'+a+'</p>')),L.setItem('bok',JSON.stringify(B)),$('.bno').click(),$('.bq').longPress('D=E=0,$(".sc").fadeIn().css("margin-left",(a=$("#book li").width(),a>64?a/2+10:a-20)+"px"),$(".bq").length<20&&$(".mark").show()')):alert('书签不完整\nヾ(°ｰ°ヾ)^?啊咧？')})
$('#menu input,#logod').change(function(){a=$(this),b=a.val(),c=0;if(a.is('#fontc0'))C[c=1][4]=b;if(a.is('#fontc1'))C[c=1][5]=b;if(a.is('#fonts'))C[c=1][6]=b?b:24;if(a.is('#logor'))C[c=1][7]=b?b:0;if(a.is('#logos'))C[c=1][8]=b?b:120;if(a.is('.logof'))C[c=1][9]=b?b:'Google';if(a.is('#logod'))C[c=1][11]=b?b:'<p style="font-size:40px"><b style="color:#48f">G</b><b style="color:#e43">o</b><b style="color:#fb0">o</b><b style="color:#48f">g</b><b style="color:#3a5">l</b><b style="color:#e43">e</b></p>';if(a.is('#backs'))C[c=2][4]=b?b:270;if(a.is('#barh'))C[c=3][1]=b?b:400;if(a.is('#bart'))C[c=3][2]=b?b:300;if(a.is('#barp'))C[c=3][3]=b?b:'What';if(a.is('#bars'))C[c=3][4]=b?b:'Go';if(a.is('#bookr'))C[c=4][1]=b?b:0;if(a.is('#bookc'))C[c=4][2]=b;if(a.is('#bookn'))C[c=4][3]=b?b:5;if(a.attr('type')=='color')a.css('background',b);c&&style(c)})
$('#lgo,#engine li').longPress(function(){if(E)E=F=0,$("#menu")[0].reset(),$(".timeb,#logof,.logof,#fontc1,#logop,.logop,#logod,.backp,#about,#zz,.wqy").hide(),$("#menu").slideDown(),$("#engine,#book,#bar").slideUp(),$(".dta").html(C[0][1]),$(".logo").html((b=C[1],a=b[1])),$(a=="时间"?"#logof,.timeb":a=="文字"?"#logof,.logof":a=="图片"?"#logop":"#logod").show(),$(".timeb o").html(b[2]?"显示":"隐藏"),$(".fontc").html(b[3]?($("#fontc1").show(),"渐变"):"单色"),$("#fontc0").val(b[4]).css('background',b[4]),$("#fontc1").val(b[5]).css('background',b[5]),$("#fonts").val(b[6]),$("#logor").val(b[7]),$("#logos").val(b[8]),$(".logof").val(b[9]),$(".logop").eq(a=b[10].match(/\.(png|jp(e?)g|gif)$/i)?1:0).val(a?b[10]:"图片为base64编码").show().nextAll("o").html(a?"路径":"图片"),$("#logod").val(b[11]),$(".back").html((b=C[2],b[1]?"图片":"颜色")),$(".backc").val(b[2]).eq(0).css('background',b[2]),$(".backp").eq(a=b[3].match(/\.(png|jp(e?)g|gif)$/i)?1:0).val(a?b[3]:"图片为base64编码").show().nextAll("o").html(a?"路径":"图片"),$("#backs").val(b[4]),$(".qh").html(b[5]?"显示":"隐藏"),$("#barh").val((b=C[3],b[1])),$("#bart").val(b[2]),$("#barp").val(b[3]),$("#bars").val(b[4]),$("#bookr").val((b=C[4],b[1])),$("#bookc").val(b[2]).css('background',b[2]),$("#bookn").val(b[3])})
function getdata(a){a?$.ajax({url:'http://suggestion.baidu.com/su',type:'GET',dataType:'jsonp',data:{wd:a,cb:'su'}}):su({s:[]})}
function run(a){getdata(''),$('#bar')[0].reset(),setTimeout(function(){$('#input').blur(),self.location=a.match(/^((ht|f)tp(s?)|file|folder):\/\//i)?a:C[3][5]+a},300)}
function num(a,b,c){d=$(a).val(),$(a).val(d.substring(0,b>9?(d.length<2&&d.match(/[a-f0-9#]/i)||d.match(/[a-f0-9]+$/ig)?(d.match(/^#/)?7:6):d.length-1):b==9&&d.length<2&&d.match(/[-\d]/)||d.match(/\d+$/g)?(d.match(/^0/)?c:(b<9?b:d.match(/^-/)?4:3)):d.length-1))}
function su(a){for(var b=a.s,c='',d=$('#suglist'),e=f=b.length,g=d.find('li').length;e>0;e--)c+='<li>'+b[e-1]+'<b></b></li>';$('#close').css('display',f?'block':''),d.stop().html(f>g?c:d.html()).animate({'height':(d.find('li').height()*1.4+2)*f+3},f?30*Math.abs(g-f):60,function(){d.html(c)})}
function style(a){
if(!a||a==1)b=C[1],o=$('#lgo'),T=0,$('.lgo').html('').removeAttr('style').not('div').remove(),b[1]!='图片'?(b[1]!='自定义'?(o.css({'-webkit-background-clip':'text','-webkit-text-fill-color':'transparent','background-image':'-webkit-linear-gradient(left,'+b[4]+','+(b[3]?b[5]:b[4])+')','font-size':b[6]+'px'}),b[1]=='时间'?(T=1,o.css({'font-family':'a','height':b[6]}),b[2]&&$('#lgo').before('<p class="lgo" style="'+o.attr("style")+'opacity:0.2;position:absolute">88:88:88</p>')):o.html(b[9])):o.html(b[11])):o.html('<img src="'+b[10]+'" style="background-size:cover;border-radius:'+b[7]+'px;width:'+b[8]+'px">');
if(!a||a==2)b=C[2],$('body').css({'background-color':b[2],'background-image':'url('+(b[1]?b[3]:0)+')','background-position':0+' '+b[4]+'px'}),b[5]?$('.sx').show():$('.sx').hide();
if(!a||a==3)b=C[3],$('#input').attr('placeholder',b[3]),$('#submit').val(b[4])
if(!a||a==4)b=C[4],c=$('#book').width()/b[3],$('style').html('#book li{width:'+c+'px;height:'+(c>64?64:c)+'px}.bq,.bicon{border-radius:'+b[1]+'px}.bq,.tj{width:'+(d=(c>64?40:c*5/8))+'px;height:'+d+'px}#book p,.btext{color:'+b[2]+';font-size:'+(c>64?12:c*0.2)+'px}#input:focus{transform:'+C[3][1]+'px}@media all and (orientation:landscape){#book li{width:12.5%;height:64px}.tj,.bq{width:40px;height:40px}#book p,.btext{font-size:12px}}')
}
$(function(){var x,y,d,w,h,p,left,top,f,m,a=$('#book')[0],b=0;
a.addEventListener('touchstart',function(e){var c=$(e.target).parents('li');if(!$(e.target).is('.bq')||D||c.is('.mark')||$('#bookmark').attr('style')||b)return;d=c,m=d.index(),w=d.width(),h=d.height(),p=d.offset(),left=p.left,top=p.top;d.css({'width':w,'height':h,'position':'fixed',opacity:.8,left:left,top:top}).before('<li class="bok"></li>'),f=$('.bok');var g=e.targetTouches[0];x=g.pageX,y=g.pageY,w/=2,h/=2,b=1},{passive:true});
a.addEventListener('touchmove',function(e){if(b){var g=e.targetTouches[0],l=left+g.pageX-x,t=top+g.pageY-y;d.css({'left':l,'top':t}),l+=w,t+=h,$(a).children().not(d).not(f).not('.mark').each(function(i){var i=$(this),p=i.offset();if(p.left<l&&l<p.left+i.width()&&p.top<t&&t<p.top+i.height())return i.next('.bok').length?f.insertBefore(this):f.insertAfter(this),!1})}},{passive:true});
a.addEventListener('touchend',function(){if(b){var p=f.offset();d.animate({'left':p.left,'top':p.top},200,function(){if($('.bok').length){d.removeAttr('style'),f.replaceWith(d),n=d.index(),b=0;B.splice(n+(m-n<0&&1),0,B[m]),B.splice(m+(m-n>0&&1),1),L.setItem('bok',JSON.stringify(B))}})}},{passive:true})
$(document).click(function(e){var a=$(e.target),b=a.parent(),c=a.html()
if($('.mark').attr('style')&&!a.is('.sc'))$('.sc').css('-webkit-animation','shensuo1 0.3s'),$('.tj').animate({'marginTop':50,'opacity':0},300,function(){$('.mark,.sc').removeAttr('style'),$(this).css({'margin-top':'','opacity':''})}),a.is('.tj')||a.is('.bq')?($('#bookmark,#bar').slideToggle(),$('#mark')[0].reset(),$('.kicon').hide(),a.is('.bq')?($('.bbox p').html('编辑书签'),cat=b.index()-1,c=B[cat],$('.btext').html(c[0]),$('.ktext').val(c[0]),$('.khttp').val(c[1]),$('.bicon').attr('src',c[2]),$('#mark o').html(c[2].match(/\.(png|jp(e?)g|gif)$/i)?($('.kicon').eq(1).val(c[2]).show(),'路径'):($('.kicon').eq(0).val('图片为base64编码').show(),'图片'))):($('.bbox p').html('添加书签'),cat=99,$('.btext').html('预览'),$('.bicon').attr('src','img/jz.gif'),$('#mark o').html('图片'),$('.kicon').eq(0).show())):D=E=1
if(a.is('.logo'))a.html(C[1][1]=c=='时间'?(d='.logof,.timeb','文字'):c=='文字'?(d='#logof,#logop,.logof','图片'):c=='图片'?(d='#logop,#logod','自定义'):(d='#logod,#logof,.timeb','时间')),$(d).toggle(),style(1)
if(a.is('.set'))b=a.parents(),$(b.is('#mark')?($('.bicon').attr('src','img/jz.gif'),'.kicon'):b.is('#logop')?'.logop':'.backp').toggle().val(''),a.html(c=='图片'?'路径':'图片')
if(a.is('.sc'))a.remove(),b.find('div').animate({'marginTop':50,'opacity':0},300,function(){b.remove()}),B.splice(b.index(),1),L.setItem('bok',JSON.stringify(B))
if(a.is('#engine li'))C[3][5]=a.attr('msg'),$('#engine,#bar').slideToggle(),L.setItem('mnu',JSON.stringify(C))
if(a.is('.fontc'))a.html(c=='单色'?(d=1,'渐变'):(d=0,'单色')),$('#fontc1').toggle(),C[1][3]=d,style(1)
if(a.is('.mno'))$('#menu,#bar,#book').slideToggle(),!E&&(E=1,C=JSON.parse(L.mnu),style(0))
if(a.is('.about'))F=F?0:1,$('#about').toggle(),$('#menus').animate({scrollTop:(F?500:0)},300)
if(a.is('.bno'))$('#bar,#bookmark').slideToggle(function(){$(this).attr('style','')}),D=E=1
if(a.is('.timeb o'))a.html(c=='隐藏'?(d=1,'显示'):(d=0,'隐藏')),C[1][2]=d,style(1)
if(a.is('.back'))a.html(c=='图片'?(d=0,'颜色'):(d=1,'图片')),C[2][1]=d,style(2)
if(a.is('.myes'))L.setItem('mnu',JSON.stringify(C)),$('.mno').click(),E=1
if(a.is('.qh'))a.html(c=='隐藏'?(d=1,'显示'):(d=0,'隐藏')),C[2][5]=d,style(2)
if(a.is('#clear'))$('#input').val('').focus(),$('#bar')[0].reset()
if(a.is('#lgo *')&&E||a.is('#lgo')&&E)self.location='folder://'
if(a.is('.wyes'))L.removeItem('mnu'),location.reload()
if(a.is('.bq')&&D)self.location=a.attr('msg')
if(a.is('.wno'))$('.wqy').slideUp()
if(a.is('.sx'))location.reload()
if(a.is('#close'))getdata('')
})})
